snippets: update getopts, remove wildcard

diff --git a/snippets/sh-mode/getopts b/snippets/sh-mode/getopts
--- a/snippets/sh-mode/getopts
+++ b/snippets/sh-mode/getopts
@@ -2,7 +2,8 @@ while getopts ":hf:" arg; do
 	case $arg in
 	h) echo "help" ;;
 	f) echo "$OPTARG" ;;
-        *) echo "invalid option"; exit 1 ;;
+        :)  echo "Mandatory argument missing for given flag $OPTARG"; exit 1;;
+        \?) echo "Unknown flag";  exit 1;;
 	esac
 done
 shift $((OPTIND - 1)) # allow positional arguments
